### ISSUE TITLE
Linking fails on GHC 7.8.3 for CV 0.3.7 and openCV24

### ISSUE THREAD

**Issue by vlatkoB** [aleator/CV#48]
Hello,

I forked locally 0.3.7 from Hackage to make it build with GHC 7.8.2.20140609-1 (TomMD #45) and all compiled well. However, with GHC 7.8.3 compiling goes well, but linking fails with 

cvWrapLEO.c:(.text+0x3bf1): undefined reference to `toNormalizedCoords'
cvWrapLEO.c:(.text+0x3c1a): undefined reference to`eucNorm'
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o): In function `haarFilter':
cvWrapLEO.c:(.text+0x50eb): undefined reference to`imin'
cvWrapLEO.c:(.text+0x50f7): undefined reference to `imax'
cvWrapLEO.c:(.text+0x5114): undefined reference to`imin'
cvWrapLEO.c:(.text+0x5120): undefined reference to `imax'
cvWrapLEO.c:(.text+0x513d): undefined reference to`imin'
cvWrapLEO.c:(.text+0x5149): undefined reference to `imax'
cvWrapLEO.c:(.text+0x5166): undefined reference to`imin'
cvWrapLEO.c:(.text+0x5172): undefined reference to `imax'
cvWrapLEO.c:(.text+0x51b4): undefined reference to`blurGet2D'
cvWrapLEO.c:(.text+0x51d3): undefined reference to `blurGet2D'
cvWrapLEO.c:(.text+0x51fe): undefined reference to`blurGet2D'
cvWrapLEO.c:(.text+0x5229): undefined reference to `blurGet2D'
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o): In function`haar_at':
cvWrapLEO.c:(.text+0x52e6): undefined reference to `blurGet2D'
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o):cvWrapLEO.c:(.text+0x5304): more undefined references to`blurGet2D' follow
../Tst./.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o): In function `susanEdge':
cvWrapLEO.c:(.text+0x6625): undefined reference to`susanValue'
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o): In function `localBinaryPattern':
cvWrapLEO.c:(.text+0x748d): undefined reference to`blurGet2D'
cvWrapLEO.c:(.text+0x74b2): undefined reference to `blurGet2D'
cvWrapLEO.c:(.text+0x74e7): undefined reference to`blurGet2D'
cvWrapLEO.c:(.text+0x7519): undefined reference to `blurGet2D'
cvWrapLEO.c:(.text+0x754b): undefined reference to`blurGet2D'
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o):cvWrapLEO.c:(.text+0x7580): more undefined references to `blurGet2D' follow
.../Tst/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/CV-0.3.7/libHSCV-0.3.7.a(cvWrapLEO.o): In function`selectiveAvgFilter':
cvWrapLEO.c:(.text+0x8204): undefined reference to `calcSelectiveAvg'
collect2: ld returned 1 exit status

Any ideas?

Best regards,

vlatko
